language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - pycodestyle gadget
  - coverage run --omit=gadget/lib/*,gadget/bin/* --source=gadget -m pytest tests/
  - coveralls
